language: go
services:
        - docker

jobs:
        - name: firstjob
          script: 
               - echo Hello
               - env
        - name: secondjob 
          script: 
               - echo World
               - env
