language: go
services:
        - docker

jobs:
    include:
        - name: firstjob
          script: 
               - echo Hello
               - env
        - name: secondjob 
          script: 
               - echo World
               - env
        - name: docker 
          script: 
              - docker version
              - docker-compose --version
